# Usamos Nginx ligero
FROM nginx:alpine

# Eliminamos la configuración por defecto de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copiamos nuestra configuración personalizada
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiamos todos tus archivos estáticos (HTML, CSS, JS) al servidor
# NOTA: Asegúrate de que index.html, css/ y js/ estén en la misma carpeta que este Dockerfile
COPY . /usr/share/nginx/html

# Exponemos el puerto 80 (interno)
EXPOSE 80